### ISSUE TITLE
the generated SVDs name tags does not comply with the ANSI C identifier naming restrictions

### ISSUE THREAD

**Issue by tarek-bochkati** [Jegeva/ads2svd#4]
Hi,

according to [SVD File Conventions](https://www.keil.com/pack/doc/CMSIS/SVD/html/svd_xml_conventions_gr.html#Names)
> All name tags must comp ly with the ANSI C identifier naming restrictions. In particular, they must not contain any spaces or special characters. This is necessary to support the generation of device header files thus providing consistency between the names being shown by the debugger and the symbols being used in the CMSIS compliant target software.

for example in this generated [Cortex_M3.svd](https://github.com/jwinarske/ads-svd/blob/master/svd/Cores/Cortex_M3.svd#L7):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<device xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
        schemaVersion="1.3"
        xs:noNamespaceSchemaLocation="CMSIS-SVD.xsd">
   <vendor>ARM Ltd.</vendor>
   <vendorID>ARM</vendorID>
   <name>Cortex-M3</name>
```

the name.text() "Cortex-M3" does not comply with ANSI C identifier naming restrictions and is reported by the XSD validator.

is there a way to transform this automatically, like using underscore instead of '-'

Thanks,
Tarek

**Comment by Jegeva** [comment]
fixed in master, can you check if its ok on your side ?

**Comment by tarek-bochkati** [comment]
Thanks @Jegeva 
sneaking into https://github.com/Jegeva/ads2svd/commit/4d7de1fa9c7d47c8bd474f72e9519a9ac02b13fe
it seems to fix the issue.
